name: "Build"
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    env:
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Install deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: coinor-cbc coinor-libcbc-dev
          version: 1.0

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Compile
        run: cargo build --release

      - name: Archive artefacts
        uses: actions/upload-artifact@v4
        with:
          name: kural
          path: target/release/kural
